{{- if .Values.vpa.enabled }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "influxdb.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}  # Off, Initial, Auto
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu", "memory"]
{{- end }}
